const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

async function checkEmptyBlog() {
  try {
    // Check the empty blog
    const blog = await prisma.blog.findUnique({
      where: { id: "cmg6eeczh00011kzzwk7zhlf8" },
      select: {
        id: true,
        title: true,
        slug: true,
        excerpt: true,
        content: true,
        coverImage: true,
        tags: true,
        metadata: true,
        readingTime: true,
        isPublished: true,
        publishedAt: true,
        createdAt: true,
        updatedAt: true,
        stemCategory: true,
        viralScore: true,
        socialShares: true,
        competitorRank: true,
        romanianMarketFit: true,
        author: { select: { name: true } },
        category: { select: { name: true } },
      },
    });

    console.log("=== EMPTY BLOG INVESTIGATION ===\n");

    if (!blog) {
      console.log("❌ Blog not found with ID: cmg6eeczh00011kzzwk7zhlf8");
      return;
    }

    // Basic info
    console.log("=== BASIC INFORMATION ===");
    console.log("Blog ID:", blog.id);
    console.log("Title:", blog.title || "EMPTY");
    console.log("Slug:", blog.slug || "EMPTY");
    console.log("Created:", blog.createdAt);
    console.log("Updated:", blog.updatedAt);
    console.log("Reading Time:", blog.readingTime, "minutes");
    console.log("Is Published:", blog.isPublished);
    console.log("Published At:", blog.publishedAt || "NOT PUBLISHED");
    console.log("Cover Image:", blog.coverImage || "NONE");
    console.log("Tags:", blog.tags?.join(", ") || "NONE");
    console.log("STEM Category:", blog.stemCategory);
    console.log("Viral Score:", blog.viralScore || "NONE");
    console.log("Social Shares:", blog.socialShares);
    console.log("Competitor Rank:", blog.competitorRank || "NONE");
    console.log("Romanian Market Fit:", blog.romanianMarketFit || "NONE");
    console.log("Author:", blog.author?.name || "UNKNOWN");
    console.log("Category:", blog.category?.name || "UNKNOWN");

    // Excerpt
    console.log("\n=== EXCERPT ===");
    console.log("Excerpt length:", blog.excerpt ? blog.excerpt.length : 0);
    if (blog.excerpt) {
      console.log("Excerpt:", blog.excerpt);
    } else {
      console.log("❌ NO EXCERPT");
    }

    // AI Metadata
    console.log("\n=== AI METADATA ===");
    if (blog.metadata?.ai) {
      console.log("AI Generated:", blog.metadata.ai.aiGenerated);
      console.log("Generated By:", blog.metadata.ai.generatedBy || "UNKNOWN");
      console.log("Model Version:", blog.metadata.ai.modelVersion || "UNKNOWN");
      console.log(
        "Processing Time:",
        blog.metadata.ai.processingTime || "UNKNOWN",
        "ms"
      );
      console.log(
        "Original Prompt:",
        blog.metadata.ai.originalPrompt || "NONE"
      );
      console.log("Refinement Applied:", blog.metadata.ai.refinementApplied);
    } else {
      console.log("❌ NO AI METADATA");
    }

    // SEO Metadata
    console.log("\n=== SEO METADATA ===");
    if (blog.metadata?.seo) {
      console.log("Meta Title:", blog.metadata.seo.metaTitle || "NONE");
      console.log(
        "Meta Description:",
        blog.metadata.seo.metaDescription || "NONE"
      );
      console.log("Focus Keyword:", blog.metadata.seo.focusKeyword || "NONE");
      console.log(
        "Keywords Count:",
        blog.metadata.seo.metaKeywords?.length || 0
      );
    } else {
      console.log("❌ NO SEO METADATA");
    }

    // Content analysis
    console.log("\n=== CONTENT ANALYSIS ===");
    const wordCount = blog.content
      ? blog.content.trim().split(/\s+/).length
      : 0;
    console.log(
      "Content length (chars):",
      blog.content ? blog.content.length : 0
    );
    console.log("Word count:", wordCount);

    if (blog.content && blog.content.length > 0) {
      console.log("✅ Content exists");
      console.log(
        "First 200 characters:",
        blog.content.substring(0, 200) + "..."
      );

      // Quality metrics
      const metrics = analyzeContentQuality(blog.content);
      console.log("\nQuality Metrics:");
      console.log("  Sentences:", metrics.sentences);
      console.log("  Paragraphs:", metrics.paragraphs);
      console.log("  Avg words per sentence:", metrics.avgWordsPerSentence);
      console.log("  Has Romanian keywords:", metrics.hasRomanianKeywords);
    } else {
      console.log("❌ CONTENT IS COMPLETELY EMPTY");
    }

    // Diagnosis
    console.log("\n=== DIAGNOSIS ===");
    let issues = [];

    if (!blog.title) issues.push("Missing title");
    if (!blog.excerpt) issues.push("Missing excerpt");
    if (!blog.content || blog.content.length === 0)
      issues.push("Empty content");
    if (!blog.metadata?.ai) issues.push("Missing AI metadata");
    if (!blog.metadata?.seo) issues.push("Missing SEO metadata");

    if (issues.length === 0) {
      console.log("✅ Blog appears to be complete");
    } else {
      console.log("❌ Issues found:");
      issues.forEach(issue => console.log("  - " + issue));

      console.log("\n🔍 POSSIBLE CAUSES:");
      if (
        !blog.metadata?.ai?.processingTime ||
        blog.metadata?.ai?.processingTime < 1000
      ) {
        console.log("  - AI generation failed or was interrupted");
      }
      if (
        blog.metadata?.ai?.modelVersion === "gpt-5-mini/gpt-5-mini" &&
        (!blog.content || blog.content.length === 0)
      ) {
        console.log("  - GPT-5-mini model might have generation issues");
      }
      if (blog.createdAt.getTime() === blog.updatedAt.getTime()) {
        console.log(
          "  - Blog was never updated after creation, suggesting failed generation"
        );
      }
    }
  } catch (error) {
    console.error("Error:", error);
  } finally {
    await prisma.$disconnect();
  }
}

function analyzeContentQuality(content) {
  if (!content)
    return {
      sentences: 0,
      paragraphs: 0,
      avgWordsPerSentence: 0,
      hasRomanianKeywords: false,
    };

  const sentences = content
    .split(/[.!?]+/)
    .filter(s => s.trim().length > 0).length;
  const paragraphs = content
    .split(/\n\s*\n/)
    .filter(p => p.trim().length > 0).length;
  const words = content.split(/\s+/).length;
  const avgWordsPerSentence =
    sentences > 0 ? (words / sentences).toFixed(1) : 0;

  // Check for Romanian STEM keywords
  const romanianKeywords = [
    "știință",
    "tehnologie",
    "inginerie",
    "matematică",
    "educație",
    "copii",
    "învățare",
    "STEM",
  ];
  const hasRomanianKeywords = romanianKeywords.some(keyword =>
    content.toLowerCase().includes(keyword.toLowerCase())
  );

  return {
    sentences,
    paragraphs,
    avgWordsPerSentence,
    hasRomanianKeywords,
  };
}

checkEmptyBlog();
