/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./features/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    // Enhanced responsive breakpoints following mobile-first approach
    screens: {
      xs: "375px", // Small phones
      sm: "640px", // Large phones
      md: "768px", // Tablets
      lg: "1024px", // Small desktops
      xl: "1280px", // Large desktops
      "2xl": "1536px", // Ultra-wide screens
    },
    container: {
      center: true,
      padding: {
        DEFAULT: "1rem",
        xs: "0.75rem",
        sm: "1rem",
        md: "1.5rem",
        lg: "2rem",
        xl: "2rem",
        "2xl": "2rem",
      },
      screens: {
        xs: "375px",
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        info: {
          DEFAULT: "hsl(var(--info))",
          foreground: "hsl(var(--info-foreground))",
        },
        "high-contrast": {
          background: "hsl(var(--high-contrast-background))",
          foreground: "hsl(var(--high-contrast-foreground))",
          border: "hsl(var(--high-contrast-border))",
        },
        surface: {
          0: "hsl(var(--surface-0))",
          1: "hsl(var(--surface-1))",
          2: "hsl(var(--surface-2))",
          3: "hsl(var(--surface-3))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      spacing: {
        0.5: "0.125rem",
        1.5: "0.375rem",
        2.5: "0.625rem",
        3.5: "0.875rem",
        4.5: "1.125rem",
        5.5: "1.375rem",
        6.5: "1.625rem",
        7.5: "1.875rem",
        8.5: "2.125rem",
        9.5: "2.375rem",
        10.5: "2.625rem",
        11.5: "2.875rem",
        13: "3.25rem",
        15: "3.75rem",
        17: "4.25rem",
        18: "4.5rem",
        19: "4.75rem",
        21: "5.25rem",
        22: "5.5rem",
        23: "5.75rem",
      },
      fontSize: {
        xs: ["0.75rem", { lineHeight: "1rem" }],
        sm: ["0.875rem", { lineHeight: "1.25rem" }],
        base: ["1rem", { lineHeight: "1.5rem" }],
        lg: ["1.125rem", { lineHeight: "1.75rem" }],
        xl: ["1.25rem", { lineHeight: "1.75rem" }],
        "2xl": ["1.5rem", { lineHeight: "2rem" }],
        "3xl": ["1.875rem", { lineHeight: "2.25rem" }],
        "4xl": ["2.25rem", { lineHeight: "2.5rem" }],
        "5xl": ["3rem", { lineHeight: "1" }],
        "6xl": ["3.75rem", { lineHeight: "1" }],
        "7xl": ["4.5rem", { lineHeight: "1" }],
        "8xl": ["6rem", { lineHeight: "1" }],
        "9xl": ["8rem", { lineHeight: "1" }],
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
        fadeIn: {
          from: { opacity: 0 },
          to: { opacity: 1 },
        },
        slideInRight: {
          from: { transform: "translateX(100%)" },
          to: { transform: "translateX(0)" },
        },
        slideInLeft: {
          from: { transform: "translateX(-100%)" },
          to: { transform: "translateX(0)" },
        },
        slideInUp: {
          from: { transform: "translateY(100%)" },
          to: { transform: "translateY(0)" },
        },
        slideInDown: {
          from: { transform: "translateY(-100%)" },
          to: { transform: "translateY(0)" },
        },
        pulse: {
          "0%, 100%": { opacity: 1, transform: "scale(1)" },
          "50%": { opacity: 0.85, transform: "scale(1.05)" },
        },
        shimmer: {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(100%)" },
        },
        spin: {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        fadeIn: "fadeIn 0.3s ease-in-out forwards",
        slideInRight:
          "slideInRight 0.4s cubic-bezier(0.25, 1, 0.5, 1) forwards",
        slideInLeft: "slideInLeft 0.4s cubic-bezier(0.25, 1, 0.5, 1) forwards",
        slideInUp: "slideInUp 0.4s cubic-bezier(0.25, 1, 0.5, 1) forwards",
        slideInDown: "slideInDown 0.4s cubic-bezier(0.25, 1, 0.5, 1) forwards",
        pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        shimmer: "shimmer 2s infinite linear",
        "spin-slow": "spin 3s linear infinite",
      },
    },
  },
  plugins: [
    require("tailwindcss/plugin")(({ addBase }) => {
      addBase({
        ":root": {
          "--background": "0 0% 100%",
          "--foreground": "222.2 84% 4.9%",
          "--card": "0 0% 100%",
          "--card-foreground": "222.2 84% 4.9%",
          "--popover": "0 0% 100%",
          "--popover-foreground": "222.2 84% 4.9%",
          "--primary": "248 90% 59%",
          "--primary-foreground": "0 0% 100%",
          "--secondary": "150 84% 39%",
          "--secondary-foreground": "0 0% 100%",
          "--muted": "210 40% 96.1%",
          "--muted-foreground": "215.4 16.3% 46.9%",
          "--accent": "210 40% 96.1%",
          "--accent-foreground": "222.2 47.4% 11.2%",
          "--destructive": "0 84.2% 60.2%",
          "--destructive-foreground": "210 40% 98%",
          "--border": "214.3 31.8% 91.4%",
          "--input": "214.3 31.8% 91.4%",
          "--ring": "248 90% 59%",
          "--radius": "0.5rem",
          "--success": "142 76% 36%",
          "--success-foreground": "0 0% 100%",
          "--warning": "38 92% 50%",
          "--warning-foreground": "0 0% 100%",
          "--info": "221 83% 53%",
          "--info-foreground": "0 0% 100%",
          "--surface-0": "0 0% 100%",
          "--surface-1": "0 0% 98%",
          "--surface-2": "0 0% 96%",
          "--surface-3": "0 0% 94%",
          "--high-contrast-background": "0 0% 100%",
          "--high-contrast-foreground": "0 0% 0%",
          "--high-contrast-border": "0 0% 0%",
        },
        ".dark": {
          "--background": "222.2 84% 4.9%",
          "--foreground": "210 40% 98%",
          "--card": "222.2 84% 4.9%",
          "--card-foreground": "210 40% 98%",
          "--popover": "222.2 84% 4.9%",
          "--popover-foreground": "210 40% 98%",
          "--primary": "248 90% 59%",
          "--primary-foreground": "0 0% 100%",
          "--secondary": "150 84% 39%",
          "--secondary-foreground": "0 0% 100%",
          "--muted": "217.2 32.6% 17.5%",
          "--muted-foreground": "215 20.2% 65.1%",
          "--accent": "217.2 32.6% 17.5%",
          "--accent-foreground": "210 40% 98%",
          "--destructive": "0 62.8% 30.6%",
          "--destructive-foreground": "210 40% 98%",
          "--border": "217.2 32.6% 17.5%",
          "--input": "217.2 32.6% 17.5%",
          "--ring": "248 90% 59%",
          "--success": "142 76% 36%",
          "--success-foreground": "0 0% 100%",
          "--warning": "38 92% 50%",
          "--warning-foreground": "0 0% 0%",
          "--info": "221 83% 53%",
          "--info-foreground": "0 0% 100%",
          "--surface-0": "222.2 84% 4.9%",
          "--surface-1": "217.2 32.6% 12%",
          "--surface-2": "217.2 32.6% 17.5%",
          "--surface-3": "217.2 32.6% 22%",
          "--high-contrast-background": "0 0% 0%",
          "--high-contrast-foreground": "0 0% 100%",
          "--high-contrast-border": "0 0% 100%",
        },
        ".high-contrast": {
          "--background": "var(--high-contrast-background)",
          "--foreground": "var(--high-contrast-foreground)",
          "--border": "var(--high-contrast-border)",
          "--primary": "0 0% 0%",
          "--primary-foreground": "0 0% 100%",
          "--secondary": "0 0% 20%",
          "--secondary-foreground": "0 0% 100%",
          "--muted": "0 0% 90%",
          "--muted-foreground": "0 0% 10%",
          "--accent": "0 0% 90%",
          "--accent-foreground": "0 0% 10%",
          "--card": "0 0% 100%",
          "--card-foreground": "0 0% 0%",
        },
        ".high-contrast.dark": {
          "--background": "0 0% 0%",
          "--foreground": "0 0% 100%",
          "--border": "0 0% 100%",
          "--primary": "0 0% 100%",
          "--primary-foreground": "0 0% 0%",
          "--secondary": "0 0% 80%",
          "--secondary-foreground": "0 0% 0%",
          "--muted": "0 0% 10%",
          "--muted-foreground": "0 0% 90%",
          "--accent": "0 0% 10%",
          "--accent-foreground": "0 0% 90%",
          "--card": "0 0% 0%",
          "--card-foreground": "0 0% 100%",
        },
      });
    }),
  ],
};
