import type { Supplier } from "@/features/supplier/types/supplier";

export const mockSuppliers: Supplier[] = [
  {
    id: "supplier-1",
    userId: "user-1",
    companyName: "TechCorp Inc",
    companySlug: "techcorp-inc",
    description: "Leading tech supplier",
    website: "https://techcorp.com",
    phone: "+1234567890",
    vatNumber: "VAT123456",
    taxId: "TAX789012",
    businessAddress: "123 Tech Street",
    businessCity: "Tech City",
    businessState: "Tech State",
    businessCountry: "USA",
    businessPostalCode: "12345",
    contactPersonName: "John Doe",
    contactPersonEmail: "john@techcorp.com",
    contactPersonPhone: "+1234567890",
    yearEstablished: 2010,
    employeeCount: 50,
    annualRevenue: "5000000",
    certifications: ["ISO 9001", "ISO 14001"],
    productCategories: ["Electronics", "Software"],
    status: "PENDING",
    commissionRate: 15.0,
    paymentTerms: 30,
    minimumOrderValue: 1000.0,
    termsAccepted: true,
    privacyAccepted: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    anpcApproval: false,
    iscApproval: false,
    romanianComplianceStatus: "PENDING",
    romanianCurrency: "RON",
    romanianPaymentTerms: 30,
  },
  {
    id: "supplier-2",
    userId: "user-2",
    companyName: "EduTools Ltd",
    companySlug: "edutools-ltd",
    description: "Educational tools supplier",
    website: "https://edutools.com",
    phone: "+1987654321",
    vatNumber: "VAT654321",
    taxId: "TAX210987",
    businessAddress: "456 Education Ave",
    businessCity: "Edu City",
    businessState: "Edu State",
    businessCountry: "Canada",
    businessPostalCode: "67890",
    contactPersonName: "Jane Smith",
    contactPersonEmail: "jane@edutools.com",
    contactPersonPhone: "+1987654321",
    yearEstablished: 2015,
    employeeCount: 25,
    annualRevenue: "2000000",
    certifications: ["ISO 9001"],
    productCategories: ["Educational Materials", "STEM Kits"],
    status: "APPROVED",
    approvedAt: new Date("2024-01-15"),
    commissionRate: 12.0,
    paymentTerms: 45,
    minimumOrderValue: 500.0,
    termsAccepted: true,
    privacyAccepted: true,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-15"),
    anpcApproval: true,
    iscApproval: true,
    romanianComplianceStatus: "APPROVED",
    romanianCurrency: "RON",
    romanianPaymentTerms: 30,
  },
  {
    id: "supplier-3",
    userId: "user-3",
    companyName: "Rejected Supplies",
    companySlug: "rejected-supplies",
    description: "Rejected supplier",
    website: "https://rejected.com",
    phone: "+1122334455",
    businessAddress: "789 Fail Street",
    businessCity: "Fail City",
    businessState: "Fail State",
    businessCountry: "UK",
    businessPostalCode: "11223",
    contactPersonName: "Bob Wilson",
    contactPersonEmail: "bob@rejected.com",
    contactPersonPhone: "+1122334455",
    certifications: [],
    productCategories: ["Hardware"],
    status: "REJECTED",
    rejectionReason: "Does not meet quality standards",
    commissionRate: 15.0,
    paymentTerms: 30,
    minimumOrderValue: 1000.0,
    termsAccepted: true,
    privacyAccepted: true,
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-05"),
    anpcApproval: false,
    iscApproval: false,
    romanianComplianceStatus: "REJECTED",
    romanianCurrency: "RON",
    romanianPaymentTerms: 30,
  },
];

export const mockSuppliersResponse = {
  suppliers: mockSuppliers,
  pagination: {
    page: 1,
    limit: 20,
    total: 3,
    pages: 1,
  },
  filters: {
    statusCounts: {
      PENDING: 1,
      APPROVED: 1,
      REJECTED: 1,
      SUSPENDED: 0,
      INACTIVE: 0,
    },
  },
};
