// Complete professional products data for all categories
// This file contains the remaining products to be added to the main seeding script

export const additionalProducts = [
  // TECHNOLOGY PRODUCTS
  {
    name: "Robot de Programare pentru Copii - CodeBot Explorer",
    slug: "robot-programare-copii-codebot-explorer",
    description:
      "Robot educațional de programare pentru copii, perfect pentru învățarea conceptelor de coding și robotică. Include software de programare vizuală în limba română, senzori avansați și 50+ activități educaționale. Dezvoltă gândirea computațională, creativitatea și abilitățile de rezolvare a problemelor. Compatibil cu curriculumul românesc pentru școala primară și gimnaziu.",
    price: 459.99,
    compareAtPrice: 599.99,
    sku: "ROBOT-CODE-001",
    images: [
      "https://placehold.co/800x600/4F46E5/FFFFFF.png?text=CodeBot+Explorer",
      "https://placehold.co/800x600/4338CA/FFFFFF.png?text=Robot+Programare",
      "https://placehold.co/800x600/3730A3/FFFFFF.png?text=Coding+Kids",
    ],
    categorySlug: "technology",
    tags: [
      "robot programare",
      "programming robot",
      "coding pentru copii",
      "coding for kids",
      "robotică educațională",
      "educational robotics",
      "programare vizuală",
      "visual programming",
      "gândire computațională",
      "computational thinking",
      "curriculum românesc",
      "Romanian curriculum",
      "tehnologie educațională",
      "educational technology",
      "școala primară",
      "elementary school",
      "gimnaziu",
      "middle school",
      "senzori",
      "sensors",
      "activități educaționale",
      "educational activities",
    ],
    ageGroup: "ELEMENTARY_6_8",
    stemDiscipline: "TECHNOLOGY",
    productType: "ROBOTICS",
    learningOutcomes: ["PROBLEM_SOLVING", "CREATIVITY", "CRITICAL_THINKING"],
    romanianCompetencies: [
      "Competența digitală",
      "Competența matematică și competențele de bază în științe și tehnologie",
      "Competența de a învăța să înveți",
    ],
    romanianCurriculumAlignment: [
      "Informatică - Clasa a V-a: Algoritmi simpli",
      "Informatică - Clasa a VI-a: Programare vizuală",
      "Tehnologie - Clasa a VII-a: Robotică de bază",
    ],
    romanianEducationalLevel: "PRIMAR",
    romanianSubjectAreas: ["Informatică", "Tehnologie", "Matematică"],
    romanianMinistryApproval: true,
    romanianEducationalCertification:
      "Conformitate MECTS - Aprobare pentru utilizare educațională",
    romanianParentGuides: [
      "Ghid pentru părinți: Cum să înveți copilul să programeze",
      "Activități de coding pentru acasă",
      "Siguranța în utilizarea tehnologiei",
    ],
    romanianTeacherResources: [
      "Planuri de lecție pentru robotică educațională",
      "Activități pentru laboratorul de informatică",
      "Evaluare competențe digitale",
    ],
    featured: true,
    metaTitle: "Robot de Programare pentru Copii - CodeBot Explorer | TechTots",
    metaDescription:
      "Robot educațional de programare pentru copii cu software în română și 50+ activități. Perfect pentru învățarea coding-ului și dezvoltarea gândirii computaționale. Aprobat MECTS.",
    metaKeywords:
      "robot programare, programming robot, coding copii, coding kids, robotică educațională, educational robotics, curriculum românesc, Romanian curriculum, MECTS, aprobare minister",
    stockQuantity: 20,
    weight: 1.8,
    dimensions: { length: 30, width: 25, height: 20 },
  },
  {
    name: "Tablet Educațional STEM - SmartLearn Pro",
    slug: "tablet-educational-stem-smartlearn-pro",
    description:
      "Tablet educațional specializat pentru învățarea STEM, cu aplicații educaționale în limba română și conținut adaptat curriculumului românesc. Include 100+ aplicații educaționale, cameră HD, senzori de mișcare și sistem de control parental avansat. Perfect pentru dezvoltarea competențelor digitale și învățarea interactivă.",
    price: 699.99,
    compareAtPrice: 899.99,
    sku: "TABLET-STEM-002",
    images: [
      "https://placehold.co/800x600/7C3AED/FFFFFF.png?text=SmartLearn+Pro",
      "https://placehold.co/800x600/6D28D9/FFFFFF.png?text=Tablet+Educațional",
      "https://placehold.co/800x600/5B21B6/FFFFFF.png?text=STEM+Learning",
    ],
    categorySlug: "technology",
    tags: [
      "tablet educațional",
      "educational tablet",
      "STEM learning",
      "învățare STEM",
      "aplicații educaționale",
      "educational apps",
      "curriculum românesc",
      "Romanian curriculum",
      "tehnologie educațională",
      "educational technology",
      "control parental",
      "parental control",
      "cameră HD",
      "HD camera",
      "senzori",
      "sensors",
      "interactiv",
      "interactive",
      "competențe digitale",
      "digital skills",
      "școala primară",
      "elementary school",
    ],
    ageGroup: "ELEMENTARY_6_8",
    stemDiscipline: "TECHNOLOGY",
    productType: "ROBOTICS",
    learningOutcomes: ["PROBLEM_SOLVING", "CRITICAL_THINKING", "CREATIVITY"],
    romanianCompetencies: [
      "Competența digitală",
      "Competența de comunicare în limba maternă",
      "Competența de a învăța să înveți",
    ],
    romanianCurriculumAlignment: [
      "Informatică - Clasa a V-a: Utilizarea calculatorului",
      "Tehnologie - Clasa a VI-a: Tehnologii digitale",
      "Matematică - Clasa a VII-a: Aplicații matematice",
    ],
    romanianEducationalLevel: "PRIMAR",
    romanianSubjectAreas: [
      "Informatică",
      "Tehnologie",
      "Matematică",
      "Științe",
    ],
    romanianMinistryApproval: true,
    romanianEducationalCertification:
      "Conformitate MECTS - Aprobare pentru utilizare educațională",
    romanianParentGuides: [
      "Ghid pentru părinți: Cum să folosești tabletul educațional",
      "Siguranța online pentru copii",
      "Activități educaționale digitale",
    ],
    romanianTeacherResources: [
      "Planuri de lecție pentru tehnologie educațională",
      "Resurse digitale pentru clasă",
      "Evaluare competențe digitale",
    ],
    featured: false,
    metaTitle: "Tablet Educațional STEM - SmartLearn Pro | TechTots",
    metaDescription:
      "Tablet educațional STEM cu aplicații în română și conținut adaptat curriculumului românesc. 100+ aplicații educaționale și control parental avansat. Aprobat MECTS.",
    metaKeywords:
      "tablet educațional, educational tablet, STEM learning, curriculum românesc, Romanian curriculum, aplicații educaționale, educational apps, MECTS, aprobare minister",
    stockQuantity: 15,
    weight: 0.6,
    dimensions: { length: 25, width: 18, height: 1 },
  },

  // ENGINEERING PRODUCTS
  {
    name: "Set Construcții Inginerie - Arhitectul Viitorului",
    slug: "set-constructii-inginerie-arhitectul-viitorului",
    description:
      "Set complet de construcții pentru inginerie, cu piese magnetice și conexiuni avansate pentru construirea structurilor complexe. Include 500+ piese, ghid de construcții în limba română și 25+ proiecte educaționale. Dezvoltă abilitățile de inginerie, gândirea spațială și creativitatea. Perfect pentru învățarea conceptelor de arhitectură, inginerie civilă și design.",
    price: 329.99,
    compareAtPrice: 429.99,
    sku: "ENG-CONST-001",
    images: [
      "https://placehold.co/800x600/F59E0B/FFFFFF.png?text=Arhitectul+Viitorului",
      "https://placehold.co/800x600/D97706/FFFFFF.png?text=Construcții+Inginerie",
      "https://placehold.co/800x600/B45309/FFFFFF.png?text=Engineering+Set",
    ],
    categorySlug: "engineering",
    tags: [
      "construcții inginerie",
      "engineering construction",
      "piese magnetice",
      "magnetic pieces",
      "arhitectură",
      "architecture",
      "inginerie civilă",
      "civil engineering",
      "design",
      "design",
      "gândire spațială",
      "spatial thinking",
      "creativitate",
      "creativity",
      "curriculum românesc",
      "Romanian curriculum",
      "proiecte educaționale",
      "educational projects",
      "structuri",
      "structures",
      "școala primară",
      "elementary school",
      "gimnaziu",
      "middle school",
    ],
    ageGroup: "ELEMENTARY_6_8",
    stemDiscipline: "ENGINEERING",
    productType: "CONSTRUCTION_SETS",
    learningOutcomes: [
      "PROBLEM_SOLVING",
      "CREATIVITY",
      "CRITICAL_THINKING",
      "MOTOR_SKILLS",
    ],
    romanianCompetencies: [
      "Competența matematică și competențele de bază în științe și tehnologie",
      "Competența de inițiativă și antreprenoriat",
      "Competența de a învăța să înveți",
    ],
    romanianCurriculumAlignment: [
      "Tehnologie - Clasa a V-a: Construcții și structuri",
      "Matematică - Clasa a VI-a: Geometrie spațială",
      "Fizică - Clasa a VII-a: Forțe și mișcare",
    ],
    romanianEducationalLevel: "PRIMAR",
    romanianSubjectAreas: ["Tehnologie", "Matematică", "Fizică", "Arte"],
    romanianMinistryApproval: true,
    romanianEducationalCertification:
      "Conformitate MECTS - Aprobare pentru utilizare educațională",
    romanianParentGuides: [
      "Ghid pentru părinți: Cum să construiești cu copilul",
      "Proiecte de construcții pentru acasă",
      "Dezvoltarea gândirii spațiale",
    ],
    romanianTeacherResources: [
      "Planuri de lecție pentru inginerie educațională",
      "Activități pentru laboratorul de tehnologie",
      "Evaluare competențe de inginerie",
    ],
    featured: true,
    metaTitle: "Set Construcții Inginerie - Arhitectul Viitorului | TechTots",
    metaDescription:
      "Set complet de construcții pentru inginerie cu 500+ piese magnetice și 25+ proiecte educaționale. Perfect pentru dezvoltarea abilităților de inginerie și gândirea spațială. Aprobat MECTS.",
    metaKeywords:
      "construcții inginerie, engineering construction, piese magnetice, magnetic pieces, curriculum românesc, Romanian curriculum, MECTS, aprobare minister",
    stockQuantity: 35,
    weight: 3.2,
    dimensions: { length: 40, width: 30, height: 25 },
  },
  {
    name: "Kit Mecanică și Automatizare - Inventatorul Tânăr",
    slug: "kit-mecanica-automatizare-inventatorul-tanar",
    description:
      "Kit educațional de mecanică și automatizare pentru copii, cu piese modulare, motoare, senzori și sistem de control programabil. Include 200+ componente, ghid de montaj în limba română și 15+ proiecte practice. Dezvoltă înțelegerea principiilor mecanice, abilitățile de programare și gândirea logică. Perfect pentru învățarea conceptelor de robotică, automatizare și inginerie mecanică.",
    price: 389.99,
    compareAtPrice: 499.99,
    sku: "MECH-AUTO-002",
    images: [
      "https://placehold.co/800x600/EF4444/FFFFFF.png?text=Inventatorul+Tânăr",
      "https://placehold.co/800x600/DC2626/FFFFFF.png?text=Mecanică+Automatizare",
      "https://placehold.co/800x600/B91C1C/FFFFFF.png?text=Mechanical+Kit",
    ],
    categorySlug: "engineering",
    tags: [
      "mecanică automatizare",
      "mechanics automation",
      "kit mecanică",
      "mechanics kit",
      "piese modulare",
      "modular pieces",
      "motoare",
      "motors",
      "senzori",
      "sensors",
      "control programabil",
      "programmable control",
      "robotică",
      "robotics",
      "automatizare",
      "automation",
      "inginerie mecanică",
      "mechanical engineering",
      "curriculum românesc",
      "Romanian curriculum",
      "proiecte practice",
      "practical projects",
      "gimnaziu",
      "middle school",
    ],
    ageGroup: "MIDDLE_SCHOOL_9_12",
    stemDiscipline: "ENGINEERING",
    productType: "CONSTRUCTION_SETS",
    learningOutcomes: ["PROBLEM_SOLVING", "CRITICAL_THINKING", "LOGIC"],
    romanianCompetencies: [
      "Competența matematică și competențele de bază în științe și tehnologie",
      "Competența digitală",
      "Competența de inițiativă și antreprenoriat",
    ],
    romanianCurriculumAlignment: [
      "Tehnologie - Clasa a VII-a: Mecanica de bază",
      "Fizică - Clasa a VIII-a: Forțe și mișcare",
      "Informatică - Clasa a VIII-a: Programare și control",
    ],
    romanianEducationalLevel: "GIMNAZIU",
    romanianSubjectAreas: ["Tehnologie", "Fizică", "Informatică", "Matematică"],
    romanianMinistryApproval: true,
    romanianEducationalCertification:
      "Conformitate MECTS - Aprobare pentru utilizare educațională",
    romanianParentGuides: [
      "Ghid pentru părinți: Mecanica pentru copii",
      "Proiecte de automatizare pentru acasă",
      "Siguranța în lucrul cu componentele mecanice",
    ],
    romanianTeacherResources: [
      "Planuri de lecție pentru mecanică educațională",
      "Activități pentru laboratorul de tehnologie",
      "Evaluare competențe de mecanică",
    ],
    featured: false,
    metaTitle: "Kit Mecanică și Automatizare - Inventatorul Tânăr | TechTots",
    metaDescription:
      "Kit educațional de mecanică și automatizare cu 200+ componente și 15+ proiecte practice. Perfect pentru învățarea principiilor mecanice și abilităților de programare. Aprobat MECTS.",
    metaKeywords:
      "mecanică automatizare, mechanics automation, kit mecanică, mechanics kit, curriculum românesc, Romanian curriculum, MECTS, aprobare minister",
    stockQuantity: 28,
    weight: 2.8,
    dimensions: { length: 35, width: 28, height: 22 },
  },
];

export default additionalProducts;
