// Mathematics and Educational Books products data
// This file contains the remaining products for Mathematics and Educational Books categories

export const mathAndBooksProducts = [
  // MATHEMATICS PRODUCTS
  {
    name: "Set Jocuri Matematice Avansate - Geniul Numerelor",
    slug: "set-jocuri-matematice-avansate-geniul-numerelor",
    description:
      "Set complet de jocuri matematice avansate pentru copii, cu 20+ jocuri educaționale interactive și 100+ puzzle-uri matematice. Include jocuri de logică, geometrie, algebră și statistică, toate în limba română. Dezvoltă gândirea logică, abilitățile de calcul și înțelegerea conceptelor matematice complexe. Perfect pentru învățarea matematicii prin joc și dezvoltarea competențelor de rezolvare a problemelor.",
    price: 199.99,
    compareAtPrice: 279.99,
    sku: "MATH-GAME-001",
    images: [
      "https://placehold.co/800x600/3B82F6/FFFFFF.png?text=Geniul+Numerelor",
      "https://placehold.co/800x600/2563EB/FFFFFF.png?text=Jocuri+Matematice",
      "https://placehold.co/800x600/1D4ED8/FFFFFF.png?text=Math+Games",
    ],
    categorySlug: "mathematics",
    tags: [
      "jocuri matematice",
      "math games",
      "puzzle matematic",
      "math puzzles",
      "logică",
      "logic",
      "geometrie",
      "geometry",
      "algebră",
      "algebra",
      "statistică",
      "statistics",
      "calcul",
      "calculation",
      "gândire logică",
      "logical thinking",
      "curriculum românesc",
      "Romanian curriculum",
      "matematică prin joc",
      "math through play",
      "școala primară",
      "elementary school",
      "gimnaziu",
      "middle school",
      "rezolvare probleme",
      "problem solving",
      "competințe matematice",
      "math competitions",
    ],
    ageGroup: "ELEMENTARY_6_8",
    stemDiscipline: "MATHEMATICS",
    productType: "BOARD_GAMES",
    learningOutcomes: ["PROBLEM_SOLVING", "LOGIC", "CRITICAL_THINKING"],
    romanianCompetencies: [
      "Competența matematică și competențele de bază în științe și tehnologie",
      "Competența de a învăța să înveți",
      "Competența de inițiativă și antreprenoriat",
    ],
    romanianCurriculumAlignment: [
      "Matematică - Clasa a V-a: Numere naturale și fracții",
      "Matematică - Clasa a VI-a: Geometrie și măsuri",
      "Matematică - Clasa a VII-a: Algebră și funcții",
    ],
    romanianEducationalLevel: "PRIMAR",
    romanianSubjectAreas: ["Matematică", "Logica", "Geometrie"],
    romanianMinistryApproval: true,
    romanianEducationalCertification:
      "Conformitate MECTS - Aprobare pentru utilizare educațională",
    romanianParentGuides: [
      "Ghid pentru părinți: Cum să înveți copilul matematică prin joc",
      "Activități matematice pentru acasă",
      "Dezvoltarea gândirii logice",
    ],
    romanianTeacherResources: [
      "Planuri de lecție pentru matematică interactivă",
      "Activități pentru laboratorul de matematică",
      "Evaluare competențe matematice",
    ],
    featured: false,
    metaTitle: "Set Jocuri Matematice Avansate - Geniul Numerelor | TechTots",
    metaDescription:
      "Set complet de jocuri matematice avansate cu 20+ jocuri educaționale și 100+ puzzle-uri. Perfect pentru învățarea matematicii prin joc și dezvoltarea gândirii logice. Aprobat MECTS.",
    metaKeywords:
      "jocuri matematice, math games, puzzle matematic, math puzzles, curriculum românesc, Romanian curriculum, MECTS, aprobare minister",
    stockQuantity: 40,
    weight: 1.5,
    dimensions: { length: 30, width: 25, height: 15 },
  },
  {
    name: "Calculator Științific Educațional - Calculatorul Viitorului",
    slug: "calculator-stiintific-educational-calculatorul-viitorului",
    description:
      "Calculator științific educațional pentru copii, cu funcții avansate de calcul, grafică 3D și aplicații educaționale în limba română. Include 50+ funcții matematice, 100+ exemple practice și ghid de utilizare complet. Dezvoltă abilitățile de calcul, înțelegerea conceptelor matematice și competențele de utilizare a tehnologiei. Perfect pentru școala primară, gimnaziu și liceu.",
    price: 249.99,
    compareAtPrice: 329.99,
    sku: "CALC-SCI-002",
    images: [
      "https://placehold.co/800x600/8B5CF6/FFFFFF.png?text=Calculatorul+Viitorului",
      "https://placehold.co/800x600/7C3AED/FFFFFF.png?text=Calculator+Științific",
      "https://placehold.co/800x600/6D28D9/FFFFFF.png?text=Scientific+Calculator",
    ],
    categorySlug: "mathematics",
    tags: [
      "calculator științific",
      "scientific calculator",
      "calcul matematic",
      "mathematical calculation",
      "grafică 3D",
      "3D graphics",
      "funcții matematice",
      "mathematical functions",
      "aplicații educaționale",
      "educational apps",
      "curriculum românesc",
      "Romanian curriculum",
      "tehnologie educațională",
      "educational technology",
      "școala primară",
      "elementary school",
      "gimnaziu",
      "middle school",
      "liceu",
      "high school",
      "calcul avansat",
      "advanced calculation",
      "matematică aplicată",
      "applied mathematics",
    ],
    ageGroup: "MIDDLE_SCHOOL_9_12",
    stemDiscipline: "MATHEMATICS",
    productType: "ROBOTICS",
    learningOutcomes: ["PROBLEM_SOLVING", "LOGIC", "CRITICAL_THINKING"],
    romanianCompetencies: [
      "Competența matematică și competențele de bază în științe și tehnologie",
      "Competența digitală",
      "Competența de a învăța să înveți",
    ],
    romanianCurriculumAlignment: [
      "Matematică - Clasa a VII-a: Algebră și funcții",
      "Matematică - Clasa a VIII-a: Geometrie analitică",
      "Matematică - Clasa a IX-a: Funcții și grafice",
    ],
    romanianEducationalLevel: "GIMNAZIU",
    romanianSubjectAreas: ["Matematică", "Fizică", "Chimie", "Informatică"],
    romanianMinistryApproval: true,
    romanianEducationalCertification:
      "Conformitate MECTS - Aprobare pentru utilizare educațională",
    romanianParentGuides: [
      "Ghid pentru părinți: Cum să folosești calculatorul științific",
      "Activități de calcul pentru acasă",
      "Siguranța în utilizarea tehnologiei",
    ],
    romanianTeacherResources: [
      "Planuri de lecție pentru matematică cu calculator",
      "Activități pentru laboratorul de matematică",
      "Evaluare competențe de calcul",
    ],
    featured: false,
    metaTitle:
      "Calculator Științific Educațional - Calculatorul Viitorului | TechTots",
    metaDescription:
      "Calculator științific educațional cu funcții avansate și aplicații în română. Perfect pentru învățarea matematicii și dezvoltarea abilităților de calcul. Aprobat MECTS.",
    metaKeywords:
      "calculator științific, scientific calculator, curriculum românesc, Romanian curriculum, MECTS, aprobare minister",
    stockQuantity: 25,
    weight: 0.3,
    dimensions: { length: 20, width: 15, height: 3 },
  },

  // EDUCATIONAL BOOKS PRODUCTS
  {
    name: "Enciclopedia STEM pentru Copii - Călătorul Științei",
    slug: "enciclopedia-stem-copii-calatorul-stiintei",
    description:
      "Enciclopedie completă STEM pentru copii, cu 500+ pagini de conținut educațional în limba română, ilustrații colorate și activități interactive. Acoperă toate domeniile STEM: știință, tehnologie, inginerie și matematică. Include experimente practice, puzzle-uri educaționale și ghiduri pentru părinți și educatori. Perfect pentru dezvoltarea curiozității științifice și învățarea prin explorare.",
    price: 89.99,
    compareAtPrice: 129.99,
    sku: "BOOK-STEM-001",
    images: [
      "https://placehold.co/800x600/8B5CF6/FFFFFF.png?text=Călătorul+Științei",
      "https://placehold.co/800x600/7C3AED/FFFFFF.png?text=Enciclopedia+STEM",
      "https://placehold.co/800x600/6D28D9/FFFFFF.png?text=STEM+Encyclopedia",
    ],
    categorySlug: "educational-books",
    tags: [
      "enciclopedie STEM",
      "STEM encyclopedia",
      "cărți educaționale",
      "educational books",
      "știință pentru copii",
      "science for kids",
      "tehnologie educațională",
      "educational technology",
      "inginerie",
      "engineering",
      "matematică",
      "mathematics",
      "curriculum românesc",
      "Romanian curriculum",
      "experimente practice",
      "practical experiments",
      "puzzle educaționale",
      "educational puzzles",
      "ilustrații colorate",
      "colorful illustrations",
      "activități interactive",
      "interactive activities",
      "ghiduri părinți",
      "parent guides",
      "educatori",
      "educators",
    ],
    ageGroup: "ELEMENTARY_6_8",
    stemDiscipline: "GENERAL",
    productType: "BOARD_GAMES",
    learningOutcomes: ["PROBLEM_SOLVING", "CRITICAL_THINKING", "CREATIVITY"],
    romanianCompetencies: [
      "Competența de comunicare în limba maternă",
      "Competența matematică și competențele de bază în științe și tehnologie",
      "Competența de a învăța să înveți",
    ],
    romanianCurriculumAlignment: [
      "Științe Naturale - Clasa a V-a: Lumea vie",
      "Matematică - Clasa a VI-a: Geometrie și măsuri",
      "Tehnologie - Clasa a VII-a: Tehnologii moderne",
    ],
    romanianEducationalLevel: "PRIMAR",
    romanianSubjectAreas: [
      "Științe Naturale",
      "Matematică",
      "Tehnologie",
      "Informatică",
    ],
    romanianMinistryApproval: true,
    romanianEducationalCertification:
      "Conformitate MECTS - Aprobare pentru utilizare educațională",
    romanianParentGuides: [
      "Ghid pentru părinți: Cum să citești cu copilul",
      "Activități educaționale pentru acasă",
      "Dezvoltarea curiozității științifice",
    ],
    romanianTeacherResources: [
      "Planuri de lecție pentru educația STEM",
      "Activități pentru laboratorul de științe",
      "Evaluare competențe STEM",
    ],
    featured: false,
    metaTitle: "Enciclopedia STEM pentru Copii - Călătorul Științei | TechTots",
    metaDescription:
      "Enciclopedie completă STEM cu 500+ pagini de conținut educațional în română. Perfect pentru dezvoltarea curiozității științifice și învățarea prin explorare. Aprobat MECTS.",
    metaKeywords:
      "enciclopedie STEM, STEM encyclopedia, cărți educaționale, educational books, curriculum românesc, Romanian curriculum, MECTS, aprobare minister",
    stockQuantity: 50,
    weight: 1.8,
    dimensions: { length: 25, width: 20, height: 4 },
  },
  {
    name: "Carte de Programare pentru Copii - Codul Viitorului",
    slug: "carte-programare-copii-codul-viitorului",
    description:
      "Carte educațională de programare pentru copii, cu 300+ pagini de conținut interactiv în limba română, exemple practice și proiecte de coding. Acoperă conceptele de bază ale programării: algoritmi, variabile, bucle și funcții. Include cod real funcțional, puzzle-uri de programare și ghiduri pas cu pas. Perfect pentru învățarea programării prin joc și dezvoltarea gândirii computaționale.",
    price: 79.99,
    compareAtPrice: 109.99,
    sku: "BOOK-CODE-002",
    images: [
      "https://placehold.co/800x600/10B981/FFFFFF.png?text=Codul+Viitorului",
      "https://placehold.co/800x600/059669/FFFFFF.png?text=Programare+Copii",
      "https://placehold.co/800x600/047857/FFFFFF.png?text=Coding+Book",
    ],
    categorySlug: "educational-books",
    tags: [
      "carte programare",
      "programming book",
      "coding pentru copii",
      "coding for kids",
      "programare educațională",
      "educational programming",
      "algoritmi",
      "algorithms",
      "variabile",
      "variables",
      "bucle",
      "loops",
      "funcții",
      "functions",
      "gândire computațională",
      "computational thinking",
      "curriculum românesc",
      "Romanian curriculum",
      "proiecte coding",
      "coding projects",
      "puzzle programare",
      "programming puzzles",
      "exemple practice",
      "practical examples",
      "ghiduri pas cu pas",
      "step by step guides",
      "cod funcțional",
      "functional code",
    ],
    ageGroup: "ELEMENTARY_6_8",
    stemDiscipline: "TECHNOLOGY",
    productType: "BOARD_GAMES",
    learningOutcomes: ["PROBLEM_SOLVING", "LOGIC", "CRITICAL_THINKING"],
    romanianCompetencies: [
      "Competența digitală",
      "Competența de comunicare în limba maternă",
      "Competența de a învăța să înveți",
    ],
    romanianCurriculumAlignment: [
      "Informatică - Clasa a V-a: Algoritmi simpli",
      "Informatică - Clasa a VI-a: Programare vizuală",
      "Informatică - Clasa a VII-a: Programare text",
    ],
    romanianEducationalLevel: "PRIMAR",
    romanianSubjectAreas: ["Informatică", "Matematică", "Tehnologie"],
    romanianMinistryApproval: true,
    romanianEducationalCertification:
      "Conformitate MECTS - Aprobare pentru utilizare educațională",
    romanianParentGuides: [
      "Ghid pentru părinți: Cum să înveți copilul să programeze",
      "Activități de coding pentru acasă",
      "Dezvoltarea gândirii computaționale",
    ],
    romanianTeacherResources: [
      "Planuri de lecție pentru programare educațională",
      "Activități pentru laboratorul de informatică",
      "Evaluare competențe de programare",
    ],
    featured: false,
    metaTitle: "Carte de Programare pentru Copii - Codul Viitorului | TechTots",
    metaDescription:
      "Carte educațională de programare cu 300+ pagini de conținut interactiv în română. Perfect pentru învățarea programării prin joc și dezvoltarea gândirii computaționale. Aprobat MECTS.",
    metaKeywords:
      "carte programare, programming book, coding copii, coding kids, curriculum românesc, Romanian curriculum, MECTS, aprobare minister",
    stockQuantity: 60,
    weight: 0.8,
    dimensions: { length: 23, width: 18, height: 2 },
  },
];

export default mathAndBooksProducts;
