ALTER TABLE "Supplier"
ADD COLUMN IF NOT EXISTS "useSupplierRetailPriceAsBase" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "Supplier"
ADD COLUMN IF NOT EXISTS "plannedPromoDiscountPercentage" DOUBLE PRECISION DEFAULT 0;
